name: Deploy Hasura
on:
  push:
    paths:
      - 'nhost/hasura/migrations/**'
      - 'nhost/hasura/metadata/**'
    branches: [ main ]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Hasura CLI
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - name: Apply migrations & metadata
        env:
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_ADMIN_SECRET }}
          HASURA_GRAPHQL_ENDPOINT: ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
        working-directory](#)
î€€
