name: Deploy Hasura
on:
  push:
    paths:
      - 'hasura/migrations/**'
      - 'hasura/metadata/**'
    branches: [ main ]

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Hasura CLI
        run: curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
      - name: Apply migrations & metadata
        env:
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_ENDPOINT: ${{ secrets.HASURA_GRAPHQL_ENDPOINT }}
        run: |
          cd hasura
          echo "Endpoint: $HASURA_GRAPHQL_ENDPOINT"
          echo "Admin Secret: $HASURA_GRAPHQL_ADMIN_SECRET"
          hasura migrate apply --endpoint "$HASURA_GRAPHQL_ENDPOINT" --admin-secret "$HASURA_GRAPHQL_ADMIN_SECRET" --all-databases
          hasura metadata apply --endpoint "$HASURA_GRAPHQL_ENDPOINT" --admin-secret "$HASURA_GRAPHQL_ADMIN_SECRET"
